version: '3.8'

services:
  iot-dashboard:
    build:
      context: ./iot-dashboard-streamlit
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - iot-data:/app/data
      - iot-uploads:/app/uploads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  iot-data:
    driver: local
  iot-uploads:
    driver: local 